//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by simCommunication.rc
//
#define IDC_EDIT_YC                     3
#define IDC_SET                         4
#define IDC_LOST_UA                     5
#define IDC_CLEAR                       6
#define IDC_SAVE                        7
#define IDC_EDIT_YX                     8
#define IDC_IMPORT                      8
#define IDC_CALL                        9
#define IDC_COPY                        10
#define IDC_LOW_UA                      11
#define IDC_STARTUP                     12
#define IDC_EDIT_DD                     13
#define IDC_EXPORT                      13
#define IDC_SEND                        14
#define IDC_NORMAL_UA                   15
#define IDC_LOAD                        16
#define IDC_OUT_SET                     17
#define IDC_EDIT_AUTO                   18
#define IDC_GROUP_0                     19
#define IDC_LOST_UB                     20
#define IDC_GROUP_1                     21
#define IDC_PASTE                       22
#define IDC_LOW_UB                      23
#define IDC_REPLASE                     23
#define IDC_GROUP_2                     24
#define IDC_NORMAL_UB                   25
#define IDC_GROUP_3                     26
#define IDC_LOST_UC                     27
#define IDC_LOW_UC                      28
#define IDC_SET2                        29
#define IDC_NORMAL_UC                   30
#define IDC_LOST_UA2                    31
#define IDC_ON                          32
#define IDC_OFF                         33
#define IDC_LOW_UA2                     34
#define IDC_NORMAL_UA2                  35
#define IDC_LOST_UB2                    36
#define IDC_LOW_UB2                     37
#define IDC_NORMAL_UB2                  38
#define IDC_LOST_UC2                    39
#define IDC_LOW_UC2                     40
#define IDC_NORMAL_UC2                  41
#define IDD_ABOUTBOX                    100
#define IDD_EDIT_UNIT                   101
#define IDD_DLG_CURRENT_DISTRIBUTION    102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_OPERATE_UNIT                104
#define ID_COMM_MONITOR                 106
#define IDD_DLG_REPLACE                 111
#define IDR_MAINFRAME                   128
#define IDR_SIMCOMTYPE                  129
#define IDD_DLG_LIST_SELECT             356
#define IDR_POPUP_SYSTEMTRAY            562
#define IDR_POPUP_MAINFRAME             563
#define IDR_POPUP_OPERATER_YX           565
#define IDI_UNIT                        608
#define IDI_VAR                         609
#define IDI_FILE                        614
#define IDI_UNITDISABLE                 621
#define IDI_VARGROUP                    667
#define IDI_UNITFAULT                   668
#define IDI_VARGROUPDISABLE             669
#define IDR_POWER_NORMAL0               670
#define IDR_POWER_NORMAL1               671
#define IDR_POWER_FAIL0                 672
#define IDR_POWER_FAIL1                 673
#define IDI_TRAIN_DATA                  731
#define IDI_FAULT_DATA                  732
#define IDC_UNIT_NAME                   1001
#define IDC_PARAMETER_VALUE             1001
#define IDC_EDIT_VALUE                  1001
#define IDC_UNIT_TYPE                   1002
#define IDC_PARAMETER_ON                1002
#define IDC_GROUP_ID                    1002
#define IDC_CURRENT_VALUE               1002
#define IDC_SET_VALUE                   1002
#define IDC_UNIT_CT                     1003
#define IDC_PARAMETER_OFF               1003
#define IDC_FILENAME                    1003
#define IDC_SET_VALUE1                  1003
#define IDC_UNIT_PT                     1004
#define IDC_ANGLE_VALUE                 1004
#define IDC_VAR_NAME                    1005
#define IDC_FEED_NAME                   1005
#define IDC_SET_VALUE2                  1005
#define IDC_TEXT_FORMAT                 1006
#define IDC_SET_VALUE3                  1006
#define IDC_EDIT_UA                     1007
#define IDC_EDIT_UB                     1008
#define IDC_TEXT_OFF                    1008
#define IDC_EDIT_UC                     1009
#define IDC_TEXT_ON                     1009
#define IDC_PICTURE_OFF                 1010
#define IDC_PICTURE_ON                  1011
#define IDC_OPERATE_OFF                 1012
#define IDC_OPERATE_ON                  1013
#define IDC_SATRTUP                     1013
#define IDC_EDIT_UA1                    1013
#define IDC_CONFIRM_OFF                 1014
#define IDC_EDIT_STARTUP_DELAY_SECOND   1014
#define IDC_EDIT_UB1                    1014
#define IDC_LIST                        1015
#define IDC_EDIT_UC1                    1015
#define IDC_CONFIRM_ON                  1016
#define IDC_NORMAL_UA1                  1016
#define IDC_NEW                         1016
#define IDC_FEED_LIST                   1016
#define IDC_OUT_LIST                    1016
#define IDC_SCENE_PROMPT                1017
#define IDC_NORMAL_UB1                  1017
#define IDC_DEL                         1017
#define IDC_TRAIN_LIST                  1017
#define IDC_NORMAL_UC1                  1018
#define IDC_EDIT                        1018
#define IDC_TRANSMISSION_LIST           1018
#define IDC_LOST_UA1                    1019
#define IDC_CLON                        1019
#define IDC_LOST_UB1                    1020
#define IDC_EDIT_OLD                    1020
#define IDC_LOST_UC1                    1021
#define IDC_LOW_UA1                     1022
#define IDC_LOW_UB1                     1023
#define IDC_LOW_UC1                     1024
#define IDC_FILE_SELECT                 1025
#define IDC_EDIT_UA2                    1025
#define IDC_EDIT_NEW                    1025
#define IDC_EDIT_UB2                    1026
#define IDC_EDIT_FEED_NAME              1028
#define IDC_EDIT_1T_HI_CURRENT_MAX_VALUE 1028
#define IDC_EDIT_1T_HI_VOLTAGE_VALUEK   1029
#define IDC_EDIT_1T_HI_VOLTAGE_CHANGE_RATE 1030
#define IDC_EDIT_1T_GEAR                1030
#define IDC_EDIT_IN_FEED_NAME           1031
#define IDC_EDIT_1T_LO_VOLTAGE_CHANGE_RATE 1031
#define IDC_EDIT_1T_TEMP_1              1031
#define IDC_EDIT_OUT_FEED_NAME          1032
#define IDC_EDIT_2T_HI_CURRENT_MAX_VALUE 1032
#define IDC_EDIT_2T_LO_VOLTAGE_CHANGE_RATE 1032
#define IDC_EDIT_UC2                    1033
#define IDC_EDIT_1T_TEMP_2              1033
#define IDC_EDIT_2T_HI_VOLTAGE_VALUEK   1034
#define IDC_EDIT_2T_GEAR                1035
#define IDC_EDIT_1T_LOA_VOLTAGE_CHANGE_RATE 1036
#define IDC_EDIT_2T_TEMP_1              1036
#define IDC_EDIT_2T_TEMP_2              1037
#define IDC_EDIT_1T_LOB_VOLTAGE_CHANGE_RATE 1040
#define IDC_EDIT_2T_HI_VOLTAGE_CHANGE_RATE 1049
#define IDC_EDIT_FREE_TRAIN_STARTUP_DELAY_SECOND 1051
#define IDC_EDIT_FREE_TRANSMISSION_CURRENT_CHANGE_RATE 1052
#define IDC_EDIT_FREE_TRANSMISSION_STARTUP_DELAY_SECOND 1053
#define IDC_EDIT_2T_LOA_VOLTAGE_CHANGE_RATE 1053
#define IDC_EDIT_FAULT_TRANSMISSION_STARTUP_DELAY_SECOND 1054
#define IDC_EDIT_2T_LOB_VOLTAGE_CHANGE_RATE 1054
#define IDC_EDIT_FREE_TRANSMISSION_CONTINUED_SECONDS 1055
#define IDC_EDIT_CURRENT_CHANGE_RATE0   1056
#define IDC_EDIT_CURRENT_CHANGE_RATE1   1057
#define IDC_EDIT_1T_LOA_VOLTAGE_VALUEK  1057
#define IDC_EDIT_1T_LO_VOLTAGE_VALUEK   1057
#define IDC_EDIT_CURRENT_CHANGE_RATE2   1058
#define IDC_EDIT_CURRENT_CHANGE_RATE3   1059
#define IDC_EDIT_1T_LOA_CURRENT_MAX_VALUE 1059
#define IDC_EDIT_1T_LO_CURRENT_MAX_VALUE 1059
#define IDC_EDIT_CURRENT_CHANGE_RATE4   1060
#define IDC_EDIT_2T_LOA_VOLTAGE_VALUEK  1060
#define IDC_EDIT_2T_LO_VOLTAGE_VALUEK   1060
#define IDC_EDIT_CURRENT_CHANGE_RATE5   1061
#define IDC_EDIT_CURRENT_CHANGE_RATE6   1062
#define IDC_EDIT_2T_LOA_CURRENT_MAX_VALUE 1062
#define IDC_EDIT_2T_LO_CURRENT_MAX_VALUE 1062
#define IDC_EDIT_CURRENT_CHANGE_RATE7   1063
#define IDC_EDIT_1T_LOB_VOLTAGE_VALUEK  1063
#define IDC_EDIT_NOLOAD_CURRENT_CHANGE_RATE 1063
#define IDC_EDIT_CURRENT_CHANGE_RATE8   1064
#define IDC_EDIT_ON_ID_CURRENT_SCALE    1064
#define IDC_EDIT_CURRENT_CHANGE_RATE9   1065
#define IDC_EDIT_1T_LOB_CURRENT_MAX_VALUE 1065
#define IDC_EDIT_ON_IG_CURRENT_SCALE    1065
#define IDC_EDIT_2T_LOB_VOLTAGE_VALUEK  1066
#define IDC_EDIT_OFF_ID_CURRENT_SCALE   1066
#define IDC_EDIT_OFF_IG_CURRENT_SCALE   1067
#define IDC_EDIT_2T_LOB_CURRENT_MAX_VALUE 1068
#define IDC_IN_SET                      1078
#define IDC_IN_LIST                     1079
#define IDC_WND                         1150
#define IDC_TITLE                       1231
#define IDD_DLG_MESSAGE_BOX             5003
#define IDD_EDIT_VAR                    5004
#define IDD_OPERATE_PARAMETER           5005
#define IDD_PARAMETER_ONOFF             5006
#define IDD_PARAMETER_INPUT             5007
#define IDC_PROGRESS                    5009
#define IDD_DLG_TRAIN                   5014
#define IDD_DLG_FREE_TRAIN              5014
#define IDD_DLG_INLINE_VOTLAGE          5015
#define IDD_DLG_SCENE_FILE_SELECT       5018
#define IDD_SCENE_PICTURE               5019
#define IDD_DLG_FREE_TRANSMISSION       5020
#define IDD_DLG_FAULT_TRANSMISSION      5027
#define IDD_DLG_SIM_TRAIN               5028
#define IDD_DLG_PT_VOLTAGE              5038
#define IDD_DLG_CURRENT                 5039
#define IDD_DLG_FREE_TRANSMISSION_LIST  5040
#define IDD_DLG_FREE_TRAIN_LIST         5041
#define IDD_DLG_POWER_MONITOR           5042
#define IDD_DLG_POWER_THUMBNAIL         5071
#define IDC_EDIT_AVER_CURRENT           10043
#define IDC_EDIT_AVER_ANGLE             10046
#define IDC_EDIT_FREE_TRAIN_CURRENT_CHANGE_RATE 10047
#define IDC_EDIT_TRAIN_DIRECTION        10065
#define IDC_EDIT_IN_CONTINUED_SECONDS   10066
#define IDC_EDIT_CHANGE_CONTINUED_SECOND 10067
#define IDC_EDIT_OUT_CONTINUED_SECONDS  10068
#define IDC_EDIT_FEED_A_PHASE           10069
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE0 10069
#define IDC_EDIT_FEED_B_PHASE           10070
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE0 10070
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE1 10071
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE2 10072
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE1 10073
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE2 10074
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE3 10075
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE4 10076
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE3 10077
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE4 10078
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE5 10079
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE6 10080
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE5 10081
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE6 10082
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE7 10083
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE7 10084
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE8 10085
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE8 10086
#define IDC_EDIT_IN_CURRENT_CHANGE_RATE9 10087
#define IDC_EDIT_OUT_CURRENT_CHANGE_RATE9 10088
#define ID_OPERATER_FAR                 32771
#define ID_OPERATER_ON                  32772
#define ID_SIM_MODE_FREE                32773
#define ID_EDIT_UNIT                    32775
#define ID_TRANSMISSION_BEGIN           32776
#define ID_SIM_MODE_TEACH               32777
#define ID_OPERATER_REVERT              32778
#define ID_OPERATER_OFF                 32779
#define ID_TRAIN_BEGIN                  32780
#define ID_TRAIN_SIM                    32780
#define ID_OPERATER_LOCAL               32781
#define ID_TRAIN_END                    32782
#define ID_TRAIN_FREE                   32782
#define ID_FILE_LOAD                    32783
#define ID_TRANSMISSION_END             32784
#define ID_POWER_CLEAR                  32784
#define ID_OPERATER_YX                  32785
#define ID_OPERATER_PARAMETER           32786
#define ID_SHOW_WINDOW                  32790
#define ID_TRANSMISSION_FAULT           32791
#define ID_TRAIN_MODE_SIM               32792
#define ID_TRAIN_MODE_FREE              32793
#define ID_1_IN_LOSS_VOTLAGE            32794
#define ID_2_IN_LOSS_VOTLAGE            32795
#define ID_HANDCART_ON                  32796
#define ID_HANDCART_OFF                 32797
#define ID_BREAK_DISABLE                32798
#define ID_OPERATER_YX_LOCK             32799
#define ID_OPERATER_YX_UNLOCK           32800
#define ID_PARAMETER_SAVE               32801
#define ID_PARAMETER_LOAD               32802
#define ID_TRANSMISSION_FEED            32804
#define ID_IN_VOTLAGE                   32805
#define ID_PT_VOTLAGE                   32806
#define ID_CURRENT                      32807
#define ID_POWER_MONITOR                32808
#define ID_UNIT_CLEAR                   32809
#define ID_OPERATER_YX_ON               32814
#define ID_OPERATER_YX_OFF              32815
#define ID_OPERATER_YX_ABNORMAL         32816
#define ID_OPERATER_YX_NORMAL           32817
#define ID_SCENE_OPERATE                32818
#define ID_OPERATER_YX_THUMBNAIL        32878

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
